insert into departamento (id, nombre, tipo) values (1, 'Legal', 2);
insert into departamento (id, nombre, tipo) values (2, 'Support', 10);
insert into departamento (id, nombre, tipo) values (3, 'Marketing', 1);
insert into departamento (id, nombre, tipo) values (4, 'Research and Development', 9);
insert into departamento (id, nombre, tipo) values (5, 'Training', 5);
insert into departamento (id, nombre, tipo) values (6, 'Support', 3);
insert into departamento (id, nombre, tipo) values (7, 'Legal', 7);
insert into departamento (id, nombre, tipo) values (8, 'Marketing', 1);
insert into departamento (id, nombre, tipo) values (9, 'Services', 6);
insert into departamento (id, nombre, tipo) values (10, 'Research and Development', 4);
insert into departamento (id, nombre, tipo) values (11, 'Business Development', 10);
insert into departamento (id, nombre, tipo) values (12, 'Services', 7);
insert into departamento (id, nombre, tipo) values (13, 'Sales', 4);
insert into departamento (id, nombre, tipo) values (14, 'Research and Development', 9);
insert into departamento (id, nombre, tipo) values (15, 'Accounting', 9);
insert into departamento (id, nombre, tipo) values (16, 'Human Resources', 1);
insert into departamento (id, nombre, tipo) values (17, 'Product Management', 5);
insert into departamento (id, nombre, tipo) values (18, 'Training', 3);
insert into departamento (id, nombre, tipo) values (19, 'Legal', 10);
insert into departamento (id, nombre, tipo) values (20, 'Accounting', 2);
insert into departamento (id, nombre, tipo) values (21, 'Legal', 1);
insert into departamento (id, nombre, tipo) values (22, 'Business Development', 10);
insert into departamento (id, nombre, tipo) values (23, 'Training', 1);
insert into departamento (id, nombre, tipo) values (24, 'Marketing', 1);
insert into departamento (id, nombre, tipo) values (25, 'Engineering', 1);
insert into departamento (id, nombre, tipo) values (26, 'Human Resources', 7);
insert into departamento (id, nombre, tipo) values (27, 'Training', 10);
insert into departamento (id, nombre, tipo) values (28, 'Research and Development', 8);
insert into departamento (id, nombre, tipo) values (29, 'Business Development', 7);
insert into departamento (id, nombre, tipo) values (30, 'Training', 5);
insert into departamento (id, nombre, tipo) values (31, 'Training', 2);
insert into departamento (id, nombre, tipo) values (32, 'Marketing', 2);
insert into departamento (id, nombre, tipo) values (33, 'Legal', 4);
insert into departamento (id, nombre, tipo) values (34, 'Support', 6);
insert into departamento (id, nombre, tipo) values (35, 'Product Management', 10);
insert into departamento (id, nombre, tipo) values (36, 'Business Development', 4);
insert into departamento (id, nombre, tipo) values (37, 'Research and Development', 9);
insert into departamento (id, nombre, tipo) values (38, 'Support', 10);
insert into departamento (id, nombre, tipo) values (39, 'Engineering', 5);
insert into departamento (id, nombre, tipo) values (40, 'Accounting', 1);
insert into departamento (id, nombre, tipo) values (41, 'Legal', 9);
insert into departamento (id, nombre, tipo) values (42, 'Engineering', 8);
insert into departamento (id, nombre, tipo) values (43, 'Training', 10);
insert into departamento (id, nombre, tipo) values (44, 'Product Management', 3);
insert into departamento (id, nombre, tipo) values (45, 'Support', 9);
insert into departamento (id, nombre, tipo) values (46, 'Product Management', 7);
insert into departamento (id, nombre, tipo) values (47, 'Services', 8);
insert into departamento (id, nombre, tipo) values (48, 'Product Management', 8);
insert into departamento (id, nombre, tipo) values (49, 'Engineering', 7);
insert into departamento (id, nombre, tipo) values (50, 'Engineering', 1);
insert into departamento (id, nombre, tipo) values (51, 'Business Development', 7);
insert into departamento (id, nombre, tipo) values (52, 'Marketing', 9);
insert into departamento (id, nombre, tipo) values (53, 'Legal', 3);
insert into departamento (id, nombre, tipo) values (54, 'Human Resources', 2);
insert into departamento (id, nombre, tipo) values (55, 'Sales', 8);
insert into departamento (id, nombre, tipo) values (56, 'Training', 3);
insert into departamento (id, nombre, tipo) values (57, 'Sales', 6);
insert into departamento (id, nombre, tipo) values (58, 'Support', 3);
insert into departamento (id, nombre, tipo) values (59, 'Services', 4);
insert into departamento (id, nombre, tipo) values (60, 'Business Development', 9);
insert into departamento (id, nombre, tipo) values (61, 'Business Development', 3);
insert into departamento (id, nombre, tipo) values (62, 'Research and Development', 1);
insert into departamento (id, nombre, tipo) values (63, 'Engineering', 2);
insert into departamento (id, nombre, tipo) values (64, 'Research and Development', 9);
insert into departamento (id, nombre, tipo) values (65, 'Services', 3);
insert into departamento (id, nombre, tipo) values (66, 'Services', 9);
insert into departamento (id, nombre, tipo) values (67, 'Training', 7);
insert into departamento (id, nombre, tipo) values (68, 'Services', 3);
insert into departamento (id, nombre, tipo) values (69, 'Research and Development', 8);
insert into departamento (id, nombre, tipo) values (70, 'Support', 2);
insert into departamento (id, nombre, tipo) values (71, 'Services', 1);
insert into departamento (id, nombre, tipo) values (72, 'Support', 1);
insert into departamento (id, nombre, tipo) values (73, 'Sales', 4);
insert into departamento (id, nombre, tipo) values (74, 'Training', 4);
insert into departamento (id, nombre, tipo) values (75, 'Marketing', 6);
insert into departamento (id, nombre, tipo) values (76, 'Product Management', 10);
insert into departamento (id, nombre, tipo) values (77, 'Marketing', 10);
insert into departamento (id, nombre, tipo) values (78, 'Product Management', 3);
insert into departamento (id, nombre, tipo) values (79, 'Training', 7);
insert into departamento (id, nombre, tipo) values (80, 'Product Management', 6);
insert into departamento (id, nombre, tipo) values (81, 'Sales', 9);
insert into departamento (id, nombre, tipo) values (82, 'Legal', 5);
insert into departamento (id, nombre, tipo) values (83, 'Engineering', 4);
insert into departamento (id, nombre, tipo) values (84, 'Human Resources', 10);
insert into departamento (id, nombre, tipo) values (85, 'Human Resources', 3);
insert into departamento (id, nombre, tipo) values (86, 'Marketing', 6);
insert into departamento (id, nombre, tipo) values (87, 'Sales', 3);
insert into departamento (id, nombre, tipo) values (88, 'Services', 10);
insert into departamento (id, nombre, tipo) values (89, 'Sales', 8);
insert into departamento (id, nombre, tipo) values (90, 'Training', 10);
insert into departamento (id, nombre, tipo) values (91, 'Product Management', 7);
insert into departamento (id, nombre, tipo) values (92, 'Accounting', 8);
insert into departamento (id, nombre, tipo) values (93, 'Engineering', 10);
insert into departamento (id, nombre, tipo) values (94, 'Marketing', 3);
insert into departamento (id, nombre, tipo) values (95, 'Services', 8);
insert into departamento (id, nombre, tipo) values (96, 'Legal', 8);
insert into departamento (id, nombre, tipo) values (97, 'Product Management', 8);
insert into departamento (id, nombre, tipo) values (98, 'Sales', 3);
insert into departamento (id, nombre, tipo) values (99, 'Human Resources', 7);
insert into departamento (id, nombre, tipo) values (100, 'Sales', 10);
