insert into producto (id, nombre, precio) values (1, 'Nut - Almond, Blanched, Whole', 29.8);
insert into producto (id, nombre, precio) values (2, 'Wiberg Super Cure', 19.2);
insert into producto (id, nombre, precio) values (3, 'Pork - Back, Long Cut, Boneless', 45.6);
insert into producto (id, nombre, precio) values (4, 'Skirt - 24 Foot', 45.4);
insert into producto (id, nombre, precio) values (5, 'Flower - Commercial Spider', 46.3);
insert into producto (id, nombre, precio) values (6, 'Cake - Dulce De Leche', 21.3);
insert into producto (id, nombre, precio) values (7, 'Spic And Span All Purpose', 47.4);
insert into producto (id, nombre, precio) values (8, 'Sugar - Sweet N Low, Individual', 37.0);
insert into producto (id, nombre, precio) values (9, 'Pie Shells 10', 14.0);
insert into producto (id, nombre, precio) values (10, 'Chocolate - Sugar Free Semi Choc', 26.2);
insert into producto (id, nombre, precio) values (11, 'Flavouring - Orange', 20.0);
insert into producto (id, nombre, precio) values (12, 'Juice - Lagoon Mango', 28.9);
insert into producto (id, nombre, precio) values (13, 'Eggplant - Baby', 31.5);
insert into producto (id, nombre, precio) values (14, 'Remy Red Berry Infusion', 22.8);
insert into producto (id, nombre, precio) values (15, 'Yogurt - Blueberry, 175 Gr', 13.0);
insert into producto (id, nombre, precio) values (16, 'Sauce - Balsamic Viniagrette', 36.0);
insert into producto (id, nombre, precio) values (17, 'Cookies - Oreo, 4 Pack', 13.8);
insert into producto (id, nombre, precio) values (18, 'Wine - White, Pinot Grigio', 32.1);
insert into producto (id, nombre, precio) values (19, 'Watercress', 32.3);
insert into producto (id, nombre, precio) values (20, 'Fib N9 - Prague Powder', 20.3);
insert into producto (id, nombre, precio) values (21, 'Radish - Black, Winter, Organic', 21.3);
insert into producto (id, nombre, precio) values (22, 'Salad Dressing', 46.5);
insert into producto (id, nombre, precio) values (23, 'Halibut - Whole, Fresh', 36.3);
insert into producto (id, nombre, precio) values (24, 'Tray - 12in Rnd Blk', 19.4);
insert into producto (id, nombre, precio) values (25, 'Wine - Red, Marechal Foch', 28.7);
insert into producto (id, nombre, precio) values (26, 'Water - Tonic', 46.7);
insert into producto (id, nombre, precio) values (27, 'Tomato - Tricolor Cherry', 24.9);
insert into producto (id, nombre, precio) values (28, 'Beans - Turtle, Black, Dry', 45.2);
insert into producto (id, nombre, precio) values (29, 'Cake - Mini Potato Pancake', 31.9);
insert into producto (id, nombre, precio) values (30, 'Soap - Hand Soap', 37.9);
insert into producto (id, nombre, precio) values (31, 'Scallops - In Shell', 40.3);
insert into producto (id, nombre, precio) values (32, 'Peach - Fresh', 37.0);
insert into producto (id, nombre, precio) values (33, 'C - Plus, Orange', 32.6);
insert into producto (id, nombre, precio) values (34, 'Tea - Black Currant', 14.8);
insert into producto (id, nombre, precio) values (35, 'Red Snapper - Fillet, Skin On', 18.6);
insert into producto (id, nombre, precio) values (36, 'Wine - White, Riesling, Henry Of', 27.8);
insert into producto (id, nombre, precio) values (37, 'Asparagus - Frozen', 18.3);
insert into producto (id, nombre, precio) values (38, 'Wine - George Duboeuf Rose', 16.7);
insert into producto (id, nombre, precio) values (39, 'Milk Powder', 20.1);
insert into producto (id, nombre, precio) values (40, 'Lamb - Whole, Fresh', 49.0);
insert into producto (id, nombre, precio) values (41, 'Longos - Chicken Wings', 14.4);
insert into producto (id, nombre, precio) values (42, 'Brownies - Two Bite, Chocolate', 24.4);
insert into producto (id, nombre, precio) values (43, 'Syrup - Pancake', 24.0);
insert into producto (id, nombre, precio) values (44, 'Broom And Brush Rack Black', 39.6);
insert into producto (id, nombre, precio) values (45, 'Soup - Campbells, Beef Barley', 38.0);
insert into producto (id, nombre, precio) values (46, 'Squash - Guords', 28.9);
insert into producto (id, nombre, precio) values (47, 'Wine - Red, Harrow Estates, Cab', 44.3);
insert into producto (id, nombre, precio) values (48, 'Mints - Striped Red', 23.4);
insert into producto (id, nombre, precio) values (49, 'Gooseberry', 38.1);
insert into producto (id, nombre, precio) values (50, 'Oyster - In Shell', 12.8);
insert into producto (id, nombre, precio) values (51, 'Beef - Inside Round', 11.3);
insert into producto (id, nombre, precio) values (52, 'Gin - Gilbeys London, Dry', 44.0);
insert into producto (id, nombre, precio) values (53, 'Goldschalger', 41.8);
insert into producto (id, nombre, precio) values (54, 'Wine - Fino Tio Pepe Gonzalez', 31.9);
insert into producto (id, nombre, precio) values (55, 'Nestea - Ice Tea, Diet', 42.5);
insert into producto (id, nombre, precio) values (56, 'Dill Weed - Dry', 11.1);
insert into producto (id, nombre, precio) values (57, 'Bread - Roll, Whole Wheat', 25.7);
insert into producto (id, nombre, precio) values (58, 'Fond - Chocolate', 21.4);
insert into producto (id, nombre, precio) values (59, 'Pecan Raisin - Tarts', 21.3);
insert into producto (id, nombre, precio) values (60, 'Chocolate - Unsweetened', 13.8);
insert into producto (id, nombre, precio) values (61, 'Pheasants - Whole', 42.1);
insert into producto (id, nombre, precio) values (62, 'Beer - Paulaner Hefeweisse', 19.7);
insert into producto (id, nombre, precio) values (63, 'Creme De Banane - Marie', 27.6);
insert into producto (id, nombre, precio) values (64, 'Capon - Breast, Wing On', 20.5);
insert into producto (id, nombre, precio) values (65, 'Cheese - Havarti, Salsa', 25.4);
insert into producto (id, nombre, precio) values (66, 'Pepper - Green Thai', 49.0);
insert into producto (id, nombre, precio) values (67, 'Muffin - Carrot Individual Wrap', 49.5);
insert into producto (id, nombre, precio) values (68, 'V8 - Tropical Blend', 11.1);
insert into producto (id, nombre, precio) values (69, 'Fish - Base, Bouillion', 49.7);
insert into producto (id, nombre, precio) values (70, 'Garbage Bag - Clear', 49.3);
insert into producto (id, nombre, precio) values (71, 'Garbage Bag - Clear', 45.7);
insert into producto (id, nombre, precio) values (72, 'Bar Energy Chocchip', 15.6);
insert into producto (id, nombre, precio) values (73, 'Pepper - Red Thai', 41.6);
insert into producto (id, nombre, precio) values (74, 'Chicken - Whole', 27.6);
insert into producto (id, nombre, precio) values (75, 'Bay Leaf Fresh', 29.1);
insert into producto (id, nombre, precio) values (76, 'V8 Pet', 46.2);
insert into producto (id, nombre, precio) values (77, 'Brownies - Two Bite, Chocolate', 14.0);
insert into producto (id, nombre, precio) values (78, 'Stock - Beef, White', 39.9);
insert into producto (id, nombre, precio) values (79, 'Cleaner - Pine Sol', 17.4);
insert into producto (id, nombre, precio) values (80, 'Ecolab Digiclean Mild Fm', 29.3);
insert into producto (id, nombre, precio) values (81, 'Pork - Backs - Boneless', 49.4);
insert into producto (id, nombre, precio) values (82, 'Coconut - Shredded, Sweet', 33.2);
insert into producto (id, nombre, precio) values (83, 'Mayonnaise', 25.2);
insert into producto (id, nombre, precio) values (84, 'Pie Filling - Cherry', 47.8);
insert into producto (id, nombre, precio) values (85, 'Scallops - 20/30', 15.0);
insert into producto (id, nombre, precio) values (86, 'Chocolate Eclairs', 27.2);
insert into producto (id, nombre, precio) values (87, 'Wine - Barossa Valley Estate', 39.9);
insert into producto (id, nombre, precio) values (88, 'Cheese - Havarti, Salsa', 43.1);
insert into producto (id, nombre, precio) values (89, 'Swordfish Loin Portions', 28.8);
insert into producto (id, nombre, precio) values (90, 'Soupfoamcont12oz 112con', 36.4);
insert into producto (id, nombre, precio) values (91, 'Venison - Ground', 25.3);
insert into producto (id, nombre, precio) values (92, 'Wonton Wrappers', 30.8);
insert into producto (id, nombre, precio) values (93, 'Ostrich - Prime Cut', 20.3);
insert into producto (id, nombre, precio) values (94, 'Nestea - Ice Tea, Diet', 31.5);
insert into producto (id, nombre, precio) values (95, 'Bread - White Mini Epi', 27.6);
insert into producto (id, nombre, precio) values (96, 'Scallops - In Shell', 37.7);
insert into producto (id, nombre, precio) values (97, 'Vaccum Bag 10x13', 48.3);
insert into producto (id, nombre, precio) values (98, 'Cheese - Pont Couvert', 25.9);
insert into producto (id, nombre, precio) values (99, 'Beer - Mill St Organic', 33.8);
insert into producto (id, nombre, precio) values (100, 'Puree - Guava', 14.7);
