insert into tipo_de_departamento (id, nombre) values (1, 'Sales');
insert into tipo_de_departamento (id, nombre) values (2, 'Legal');
insert into tipo_de_departamento (id, nombre) values (3, 'Business Development');
insert into tipo_de_departamento (id, nombre) values (4, 'Services');
insert into tipo_de_departamento (id, nombre) values (5, 'Human Resources');
insert into tipo_de_departamento (id, nombre) values (6, 'Business Development');
insert into tipo_de_departamento (id, nombre) values (7, 'Training');
insert into tipo_de_departamento (id, nombre) values (8, 'Legal');
insert into tipo_de_departamento (id, nombre) values (9, 'Sales');
insert into tipo_de_departamento (id, nombre) values (10, 'Services');
insert into tipo_de_departamento (id, nombre) values (11, 'Sales');
insert into tipo_de_departamento (id, nombre) values (12, 'Legal');
insert into tipo_de_departamento (id, nombre) values (13, 'Legal');
insert into tipo_de_departamento (id, nombre) values (14, 'Marketing');
insert into tipo_de_departamento (id, nombre) values (15, 'Product Management');
insert into tipo_de_departamento (id, nombre) values (16, 'Business Development');
insert into tipo_de_departamento (id, nombre) values (17, 'Engineering');
insert into tipo_de_departamento (id, nombre) values (18, 'Services');
insert into tipo_de_departamento (id, nombre) values (19, 'Legal');
insert into tipo_de_departamento (id, nombre) values (20, 'Product Management');
insert into tipo_de_departamento (id, nombre) values (21, 'Marketing');
insert into tipo_de_departamento (id, nombre) values (22, 'Accounting');
insert into tipo_de_departamento (id, nombre) values (23, 'Sales');
insert into tipo_de_departamento (id, nombre) values (24, 'Research and Development');
insert into tipo_de_departamento (id, nombre) values (25, 'Sales');
insert into tipo_de_departamento (id, nombre) values (26, 'Engineering');
insert into tipo_de_departamento (id, nombre) values (27, 'Business Development');
insert into tipo_de_departamento (id, nombre) values (28, 'Support');
insert into tipo_de_departamento (id, nombre) values (29, 'Research and Development');
insert into tipo_de_departamento (id, nombre) values (30, 'Human Resources');
insert into tipo_de_departamento (id, nombre) values (31, 'Business Development');
insert into tipo_de_departamento (id, nombre) values (32, 'Marketing');
insert into tipo_de_departamento (id, nombre) values (33, 'Legal');
insert into tipo_de_departamento (id, nombre) values (34, 'Support');
insert into tipo_de_departamento (id, nombre) values (35, 'Accounting');
insert into tipo_de_departamento (id, nombre) values (36, 'Accounting');
insert into tipo_de_departamento (id, nombre) values (37, 'Services');
insert into tipo_de_departamento (id, nombre) values (38, 'Accounting');
insert into tipo_de_departamento (id, nombre) values (39, 'Research and Development');
insert into tipo_de_departamento (id, nombre) values (40, 'Research and Development');
insert into tipo_de_departamento (id, nombre) values (41, 'Services');
insert into tipo_de_departamento (id, nombre) values (42, 'Training');
insert into tipo_de_departamento (id, nombre) values (43, 'Legal');
insert into tipo_de_departamento (id, nombre) values (44, 'Marketing');
insert into tipo_de_departamento (id, nombre) values (45, 'Services');
insert into tipo_de_departamento (id, nombre) values (46, 'Business Development');
insert into tipo_de_departamento (id, nombre) values (47, 'Human Resources');
insert into tipo_de_departamento (id, nombre) values (48, 'Sales');
insert into tipo_de_departamento (id, nombre) values (49, 'Engineering');
insert into tipo_de_departamento (id, nombre) values (50, 'Product Management');
insert into tipo_de_departamento (id, nombre) values (51, 'Research and Development');
insert into tipo_de_departamento (id, nombre) values (52, 'Accounting');
insert into tipo_de_departamento (id, nombre) values (53, 'Legal');
insert into tipo_de_departamento (id, nombre) values (54, 'Human Resources');
insert into tipo_de_departamento (id, nombre) values (55, 'Training');
insert into tipo_de_departamento (id, nombre) values (56, 'Business Development');
insert into tipo_de_departamento (id, nombre) values (57, 'Business Development');
insert into tipo_de_departamento (id, nombre) values (58, 'Support');
insert into tipo_de_departamento (id, nombre) values (59, 'Business Development');
insert into tipo_de_departamento (id, nombre) values (60, 'Human Resources');
insert into tipo_de_departamento (id, nombre) values (61, 'Accounting');
insert into tipo_de_departamento (id, nombre) values (62, 'Support');
insert into tipo_de_departamento (id, nombre) values (63, 'Research and Development');
insert into tipo_de_departamento (id, nombre) values (64, 'Support');
insert into tipo_de_departamento (id, nombre) values (65, 'Research and Development');
insert into tipo_de_departamento (id, nombre) values (66, 'Training');
insert into tipo_de_departamento (id, nombre) values (67, 'Training');
insert into tipo_de_departamento (id, nombre) values (68, 'Support');
insert into tipo_de_departamento (id, nombre) values (69, 'Sales');
insert into tipo_de_departamento (id, nombre) values (70, 'Support');
insert into tipo_de_departamento (id, nombre) values (71, 'Product Management');
insert into tipo_de_departamento (id, nombre) values (72, 'Engineering');
insert into tipo_de_departamento (id, nombre) values (73, 'Human Resources');
insert into tipo_de_departamento (id, nombre) values (74, 'Human Resources');
insert into tipo_de_departamento (id, nombre) values (75, 'Sales');
insert into tipo_de_departamento (id, nombre) values (76, 'Legal');
insert into tipo_de_departamento (id, nombre) values (77, 'Training');
insert into tipo_de_departamento (id, nombre) values (78, 'Training');
insert into tipo_de_departamento (id, nombre) values (79, 'Marketing');
insert into tipo_de_departamento (id, nombre) values (80, 'Support');
insert into tipo_de_departamento (id, nombre) values (81, 'Product Management');
insert into tipo_de_departamento (id, nombre) values (82, 'Product Management');
insert into tipo_de_departamento (id, nombre) values (83, 'Sales');
insert into tipo_de_departamento (id, nombre) values (84, 'Training');
insert into tipo_de_departamento (id, nombre) values (85, 'Business Development');
insert into tipo_de_departamento (id, nombre) values (86, 'Human Resources');
insert into tipo_de_departamento (id, nombre) values (87, 'Legal');
insert into tipo_de_departamento (id, nombre) values (88, 'Engineering');
insert into tipo_de_departamento (id, nombre) values (89, 'Support');
insert into tipo_de_departamento (id, nombre) values (90, 'Product Management');
insert into tipo_de_departamento (id, nombre) values (91, 'Training');
insert into tipo_de_departamento (id, nombre) values (92, 'Research and Development');
insert into tipo_de_departamento (id, nombre) values (93, 'Human Resources');
insert into tipo_de_departamento (id, nombre) values (94, 'Training');
insert into tipo_de_departamento (id, nombre) values (95, 'Services');
insert into tipo_de_departamento (id, nombre) values (96, 'Services');
insert into tipo_de_departamento (id, nombre) values (97, 'Product Management');
insert into tipo_de_departamento (id, nombre) values (98, 'Sales');
insert into tipo_de_departamento (id, nombre) values (99, 'Accounting');
insert into tipo_de_departamento (id, nombre) values (100, 'Research and Development');
